site_name: SASP Fase 1 - Ampliaci√≥n de contenido

nav:
  - SASP: sostenibilidad.md
  - ODS 04: ods04-EducacionDeCalidad.md
  - ODS 09: ods09-IndustriaInnovacionEInfraestructura.md
  - ODS 12: ods12-ProduccionYConsumo.md
  - Reflexiones: reflexiones.md

theme: windmill
language: es